version: "3.9"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5432"
  web:
    image: to-do-api:latest
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DB_URL}
      NODE_ENV: development
    ports:
      - "4000:4000"
    volumes:
      - .:/app/
      - /app/node_modules
